### PR TITLE
Platform: Upgrade bunny [#86506894]

### PR DESCRIPTION
**Pull request by nas**
https://www.pivotaltracker.com/story/show/86506894

### CODE REVIEW

**Comment by nas** [comment]
\cc @mezis I intentionally didn't change the RM methods `ack` and `nack` as it is RM api and does not have to change if Bunny's api changes. In any case, I don't understand the reason behind `manual_ack`

**Comment by nas** [comment]
on staging and sent over 200 events they have been received and removed successfully from RabbitMq

**Comment by mezis** [comment]
> In any case, I don't understand the reason behind manual_ack

I think it's because RMQ messages are need to be ack'ed to be removed from a queue; the `ack` option only specified whether that was manual or automatic.
So I guess the rename makes things less confusing.

The PR looks good!

**Comment by pedrocunha** [comment]
No objections on this code either. I wonder if bumping bunny version will also help with the occasional error with subscription rejected.

**Comment by mezis** [comment]
> I wonder if bumping bunny version will also help with the occasional error "subscription rejected"

One can only hope :)

**Pull request merged**
